/**
 * Symbolic names for locations, objects and NPCs, plus the lookups built on
 * top of them. Vanilla Crystalis has no in-ROM table for any of these -
 * locations, objects and NPCs are only ever referenced by id - so unlike item
 * names (read from the ROM's message-text table) these have to live in
 * source instead.
 */

/**
 * Location id -> symbolic name. Ids absent from this table are unused slots
 * in the ROM.
 */
export const LOCATION_NAMES: ReadonlyArray<readonly [number, string]> = [
  [0x00, "MezameShrine"],
  [0x01, "Leaf_OutsideStart"],
  [0x02, "Leaf"],
  [0x03, "ValleyOfWind"],
  [0x04, "SealedCave1"],
  [0x05, "SealedCave2"],
  [0x06, "SealedCave6"],
  [0x07, "SealedCave4"],
  [0x08, "SealedCave5"],
  [0x09, "SealedCave3"],
  [0x0a, "SealedCave7"],
  [0x0c, "SealedCave8"],
  [0x0e, "WindmillCave"],
  [0x0f, "Windmill"],
  [0x10, "ZebuCave"],
  [0x11, "MtSabreWest_Cave1"],
  [0x14, "CordelPlainWest"],
  [0x15, "CordelPlainEast"],
  [0x18, "Brynmaer"],
  [0x19, "OutsideStomHouse"],
  [0x1a, "Swamp"],
  [0x1b, "Amazones"],
  [0x1c, "Oak"],
  [0x1e, "StomHouse"],
  [0x20, "MtSabreWest_Lower"],
  [0x21, "MtSabreWest_Upper"],
  [0x22, "MtSabreWest_Cave2"],
  [0x23, "MtSabreWest_Cave3"],
  [0x24, "MtSabreWest_Cave4"],
  [0x25, "MtSabreWest_Cave5"],
  [0x26, "MtSabreWest_Cave6"],
  [0x27, "MtSabreWest_Cave7"],
  [0x28, "MtSabreNorth_Main"],
  [0x29, "MtSabreNorth_Middle"],
  [0x2a, "MtSabreNorth_Cave2"],
  [0x2b, "MtSabreNorth_Cave3"],
  [0x2c, "MtSabreNorth_Cave4"],
  [0x2d, "MtSabreNorth_Cave5"],
  [0x2e, "MtSabreNorth_Cave6"],
  [0x2f, "MtSabreNorth_PrisonHall"],
  [0x30, "MtSabreNorth_LeftCell"],
  [0x31, "MtSabreNorth_LeftCell2"],
  [0x32, "MtSabreNorth_RightCell"],
  [0x33, "MtSabreNorth_Cave8"],
  [0x34, "MtSabreNorth_Cave9"],
  [0x35, "MtSabreNorth_SummitCave"],
  [0x38, "MtSabreNorth_Cave1"],
  [0x39, "MtSabreNorth_Cave7"],
  [0x3c, "Nadare_Inn"],
  [0x3d, "Nadare_ToolShop"],
  [0x3e, "Nadare_BackRoom"],
  [0x40, "WaterfallValleyNorth"],
  [0x41, "WaterfallValleySouth"],
  [0x42, "LimeTreeValley"],
  [0x43, "LimeTreeLake"],
  [0x44, "KirisaPlantCave1"],
  [0x45, "KirisaPlantCave2"],
  [0x46, "KirisaPlantCave3"],
  [0x47, "KirisaMeadow"],
  [0x48, "FogLampCave1"],
  [0x49, "FogLampCave2"],
  [0x4a, "FogLampCave3"],
  [0x4b, "FogLampCaveDeadEnd"],
  [0x4c, "FogLampCave4"],
  [0x4d, "FogLampCave5"],
  [0x4e, "FogLampCave6"],
  [0x4f, "FogLampCave7"],
  [0x50, "Portoa"],
  [0x51, "Portoa_FishermanIsland"],
  [0x52, "MesiaShrine"],
  [0x54, "WaterfallCave1"],
  [0x55, "WaterfallCave2"],
  [0x56, "WaterfallCave3"],
  [0x57, "WaterfallCave4"],
  [0x58, "TowerEntrance"],
  [0x59, "Tower1"],
  [0x5a, "Tower2"],
  [0x5b, "Tower3"],
  [0x5c, "TowerOutsideMesia"],
  [0x5d, "TowerOutsideDyna"],
  [0x5e, "TowerMesia"],
  [0x5f, "TowerDyna"],
  [0x60, "AngrySea"],
  [0x61, "BoatHouse"],
  [0x62, "JoelLighthouse"],
  [0x64, "UndergroundChannel"],
  [0x65, "ZombieTown"],
  [0x68, "EvilSpiritIsland1"],
  [0x69, "EvilSpiritIsland2"],
  [0x6a, "EvilSpiritIsland3"],
  [0x6b, "EvilSpiritIsland4"],
  [0x6c, "SaberaPalace1"],
  [0x6d, "SaberaPalace2"],
  [0x6e, "SaberaPalace3"],
  [0x70, "JoelSecretPassage"],
  [0x71, "Joel"],
  [0x72, "Swan"],
  [0x73, "SwanGate"],
  [0x78, "GoaValley"],
  [0x7c, "MtHydra"],
  [0x7d, "MtHydra_Cave1"],
  [0x7e, "MtHydra_OutsideShyron"],
  [0x7f, "MtHydra_Cave2"],
  [0x80, "MtHydra_Cave3"],
  [0x81, "MtHydra_Cave4"],
  [0x82, "MtHydra_Cave5"],
  [0x83, "MtHydra_Cave6"],
  [0x84, "MtHydra_Cave7"],
  [0x85, "MtHydra_Cave8"],
  [0x86, "MtHydra_Cave9"],
  [0x87, "MtHydra_Cave10"],
  [0x88, "Styx1"],
  [0x89, "Styx2"],
  [0x8a, "Styx3"],
  [0x8c, "Shyron"],
  [0x8e, "Goa"],
  [0x8f, "GoaFortressBasement"],
  [0x90, "Desert1"],
  [0x91, "OasisCaveMain"],
  [0x92, "DesertCave1"],
  [0x93, "Sahara"],
  [0x94, "SaharaOutsideCave"],
  [0x95, "DesertCave2"],
  [0x96, "SaharaMeadow"],
  [0x98, "Desert2"],
  [0x9c, "Pyramid_Entrance"],
  [0x9d, "Pyramid_Branch"],
  [0x9e, "Pyramid_Main"],
  [0x9f, "Pyramid_Draygon"],
  [0xa0, "Crypt_Entrance"],
  [0xa1, "Crypt_Hall1"],
  [0xa2, "Crypt_Branch"],
  [0xa3, "Crypt_DeadEndLeft"],
  [0xa4, "Crypt_DeadEndRight"],
  [0xa5, "Crypt_Hall2"],
  [0xa6, "Crypt_Draygon2"],
  [0xa7, "Crypt_Teleporter"],
  [0xa8, "GoaFortress_Entrance"],
  [0xa9, "GoaFortress_Kelbesque"],
  [0xaa, "GoaFortress_Zebu"],
  [0xab, "GoaFortress_Sabera"],
  [0xac, "GoaFortress_Tornel"],
  [0xad, "GoaFortress_Mado1"],
  [0xae, "GoaFortress_Mado2"],
  [0xaf, "GoaFortress_Mado3"],
  [0xb0, "GoaFortress_Karmine1"],
  [0xb1, "GoaFortress_Karmine2"],
  [0xb2, "GoaFortress_Karmine3"],
  [0xb3, "GoaFortress_Karmine4"],
  [0xb4, "GoaFortress_Karmine5"],
  [0xb5, "GoaFortress_Karmine6"],
  [0xb6, "GoaFortress_Karmine7"],
  [0xb7, "GoaFortress_Exit"],
  [0xb8, "OasisCave_Entrance"],
  [0xb9, "GoaFortress_Asina"],
  [0xba, "GoaFortress_Kensu"],
  [0xbb, "Goa_House"],
  [0xbc, "Goa_Inn"],
  [0xbe, "Goa_ToolShop"],
  [0xbf, "Goa_Tavern"],
  [0xc0, "Leaf_ElderHouse"],
  [0xc1, "Leaf_RabbitHut"],
  [0xc2, "Leaf_Inn"],
  [0xc3, "Leaf_ToolShop"],
  [0xc4, "Leaf_ArmorShop"],
  [0xc5, "Leaf_StudentHouse"],
  [0xc6, "Brynmaer_Tavern"],
  [0xc7, "Brynmaer_PawnShop"],
  [0xc8, "Brynmaer_Inn"],
  [0xc9, "Brynmaer_ArmorShop"],
  [0xcb, "Brynmaer_ItemShop"],
  [0xcd, "Oak_ElderHouse"],
  [0xce, "Oak_MotherHouse"],
  [0xcf, "Oak_ToolShop"],
  [0xd0, "Oak_Inn"],
  [0xd1, "Amazones_Inn"],
  [0xd2, "Amazones_ItemShop"],
  [0xd3, "Amazones_ArmorShop"],
  [0xd4, "Amazones_Elder"],
  [0xd5, "Nadare"],
  [0xd6, "Portoa_FishermanHouse"],
  [0xd7, "Portoa_PalaceEntrance"],
  [0xd8, "Portoa_FortuneTeller"],
  [0xd9, "Portoa_PawnShop"],
  [0xda, "Portoa_ArmorShop"],
  [0xdc, "Portoa_Inn"],
  [0xdd, "Portoa_ToolShop"],
  [0xde, "PortoaPalace_Left"],
  [0xdf, "PortoaPalace_ThroneRoom"],
  [0xe0, "PortoaPalace_Right"],
  [0xe1, "Portoa_AsinaRoom"],
  [0xe2, "Amazones_ElderDownstairs"],
  [0xe3, "Joel_ElderHouse"],
  [0xe4, "Joel_Shed"],
  [0xe5, "Joel_ToolShop"],
  [0xe7, "Joel_Inn"],
  [0xe8, "ZombieTown_House"],
  [0xe9, "ZombieTown_HouseBasement"],
  [0xeb, "Swan_ToolShop"],
  [0xec, "Swan_StomHut"],
  [0xed, "Swan_Inn"],
  [0xee, "Swan_ArmorShop"],
  [0xef, "Swan_Tavern"],
  [0xf0, "Swan_PawnShop"],
  [0xf1, "Swan_DanceHall"],
  [0xf2, "Shyron_Temple"],
  [0xf3, "Shyron_TrainingHall"],
  [0xf4, "Shyron_Hospital"],
  [0xf5, "Shyron_ArmorShop"],
  [0xf6, "Shyron_ToolShop"],
  [0xf7, "Shyron_Inn"],
  [0xf8, "Sahara_Inn"],
  [0xf9, "Sahara_ToolShop"],
  [0xfa, "Sahara_ElderHouse"],
  [0xfb, "Sahara_PawnShop"],
];

/** Monster/object id -> symbolic name. */
export const OBJECT_NAMES: ReadonlyArray<readonly [number, string]> = [
  [0x2a, "Mesia"],
  [0x3f, "sorcerorShot"],
  [0x4b, "wraith1"],
  [0x4d, "paralysisPowderSource"],
  [0x4f, "wraith2"],
  [0x50, "blueSlime"],
  [0x51, "weretiger"],
  [0x52, "greenJelly"],
  [0x53, "redSlime"],
  [0x54, "rockGolem"],
  [0x55, "blueBat"],
  [0x56, "greenWyvern"],
  [0x57, "vampire1"],
  [0x58, "orc"],
  [0x59, "redMosquito"],
  [0x5a, "blueMushroom"],
  [0x5b, "swampTomato"],
  [0x5c, "blueMosquito"],
  [0x5d, "swampPlant"],
  [0x5e, "giantInsect"],
  [0x5f, "largeBlueSlime"],
  [0x60, "iceZombie"],
  [0x61, "greenBrain"],
  [0x62, "greenSpider"],
  [0x63, "redWyvern"],
  [0x64, "soldier"],
  [0x65, "iceEntity"],
  [0x66, "redBrain"],
  [0x67, "iceGolem"],
  [0x68, "kelbesque1"],
  [0x69, "largeRedSlime"],
  [0x6a, "troll"],
  [0x6b, "redJelly"],
  [0x6c, "medusa"],
  [0x6d, "crab"],
  [0x6e, "medusaHead"],
  [0x6f, "bird"],
  [0x71, "redMushroom"],
  [0x72, "earthEntity"],
  [0x73, "mimic"],
  [0x74, "redSpider"],
  [0x75, "fishman"],
  [0x76, "jellyfish"],
  [0x77, "kraken"],
  [0x78, "darkGreenWyvern"],
  [0x79, "sandZombie"],
  [0x7b, "wraithShadow1"],
  [0x7c, "moth"],
  [0x7d, "sabera1"],
  [0x7e, "verticalPlatform"],
  [0x7f, "horizotalPlatform"],
  [0x80, "archer"],
  [0x81, "bomberBird"],
  [0x82, "lavaBlob"],
  [0x84, "flailGuy"],
  [0x85, "blueEye"],
  [0x86, "salamander"],
  [0x87, "sorceror"],
  [0x88, "mado1"],
  [0x89, "knight"],
  [0x8a, "devil"],
  [0x8b, "kelbesque2"],
  [0x8c, "wraithShadow2"],
  [0x8d, "glitch1"],
  [0x8e, "glitch2"],
  [0x8f, "guardianStatue"],
  [0x90, "sabera2"],
  [0x91, "tarantula"],
  [0x92, "skeleton"],
  [0x93, "mado2"],
  [0x94, "purpleEye"],
  [0x95, "flailKnight"],
  [0x96, "scorpion"],
  [0x97, "karmine"],
  [0x98, "sandBlob"],
  [0x99, "mummy"],
  [0x9a, "warlock"],
  [0x9b, "draygon1"],
  [0x9c, "statueOfSun"],
  [0x9d, "statueOfMoon"],
  [0x9e, "draygon2"],
  [0x9f, "crumblingVerticalPlatform"],
  [0xa0, "brownRobot"],
  [0xa1, "whiteRobot"],
  [0xa2, "towerSentinel"],
  [0xa3, "helicopter"],
  [0xa4, "dyna"],
  [0xa5, "vampire2"],
  [0xa6, "glitch3"],
  [0xb4, "dynaPod"],
  [0xb8, "dynaCounter"],
  [0xb9, "dynaLaser"],
  [0xba, "dynaBubble"],
  [0xbc, "vampire2Bat"],
  [0xbe, "brownRobotLaserSource"],
  [0xbf, "draygon2Fireball"],
  [0xc1, "vampire1Bat"],
  [0xc3, "giantInsectFireball"],
  [0xc4, "greenMosquito"],
  [0xc5, "kelbesque1Rock"],
  [0xc6, "sabera1Balls"],
  [0xc7, "kelbesque2Fire"],
  [0xc8, "sabera2Fire"],
  [0xc9, "sabera2Balls"],
  [0xca, "karmineBalls"],
  [0xcb, "statueBalls"],
  [0xcc, "draygon1Lightning"],
  [0xcd, "draygon2Laser"],
  [0xce, "draygon2Breath"],
  [0xe0, "birdBomb"],
  [0xe2, "greenMosquitoShot"],
  [0xe3, "paralysisBeam"],
  [0xe4, "stoneGaze"],
  [0xe5, "rockGolemRock"],
  [0xe6, "curseBeam"],
  [0xe7, "mpDrainWeb"],
  [0xe8, "fishmanTrident"],
  [0xe9, "orcAxe"],
  [0xea, "swampPollen"],
  [0xeb, "paralysisPowder"],
  [0xec, "soldierSword"],
  [0xed, "iceGolemRock"],
  [0xee, "trollAxe"],
  [0xef, "krakenInk"],
  [0xf0, "archerArrow"],
  [0xf2, "knightSword"],
  [0xf3, "mothResidue"],
  [0xf4, "brownRobotLaser"],
  [0xf5, "whiteRobotLaser"],
  [0xf6, "towerSentinelLaser"],
  [0xf7, "skeletonShot"],
  [0xf8, "blobShot"],
  [0xf9, "flailKnightFlail"],
  [0xfa, "flailGuyFlail"],
  [0xfc, "madoShuriken"],
  [0xfd, "guardianStatueMissile"],
  [0xfe, "demonWallFire"],
];

/** NPC id -> symbolic name. */
export const NPC_NAMES: ReadonlyArray<readonly [number, string]> = [
  [0x0b, "GoaSoldier"],
  [0x0d, "LeafElder"],
  [0x11, "LeafElderDaughter"],
  [0x13, "LeafRabbit"],
  [0x14, "WindmillGuard"],
  [0x15, "SleepingWindmillGuard"],
  [0x16, "Akahana"],
  [0x1b, "SkiFree"],
  [0x1d, "OakElder"],
  [0x1e, "OakMother"],
  [0x1f, "OakChild"],
  [0x23, "Aryllis"],
  [0x25, "AmazonesGuard"],
  [0x26, "AryllisRightAttendant"],
  [0x27, "AryllisLeftAttendant"],
  [0x28, "Nadare"],
  [0x2c, "DeadSkiFree"],
  [0x2d, "SoldierGuard"],
  [0x33, "PortoaThroneRoomBackDoorGuard"],
  [0x34, "PortoaPalaceFrontGuard"],
  [0x38, "PortoaQueen"],
  [0x39, "FortuneTeller"],
  [0x3a, "WaterfallCaveAdventurers"],
  [0x3d, "JoelElder"],
  [0x44, "Clark"],
  [0x4e, "ShyronGuard"],
  [0x54, "Brokahana"],
  [0x59, "SaharaBunny"],
  [0x5a, "Deo"],
  [0x5b, "SaharaElder"],
  [0x5c, "SaharaElderDaughter"],
  [0x5e, "Zebu"],
  [0x5f, "Tornel"],
  [0x60, "Stom"],
  [0x61, "MesiaRecording"],
  [0x62, "Asina"],
  [0x63, "HurtDolphin"],
  [0x64, "Fisherman"],
  [0x65, "StartledVillagerOutsideCave"],
  [0x68, "KensuInCabin"],
  [0x69, "Dolphin"],
  [0x6b, "SleepingKensu"],
  [0x6c, "KensuDisguisedAsDancer"],
  [0x6d, "KensuDisguisedAsSoldier"],
  [0x6e, "AztecaInShyron"],
  [0x70, "DeadAkahana"],
  [0x71, "DeadStomsGirlfriend"],
  [0x72, "DeadStom"],
  [0x74, "KensuInSwan"],
  [0x75, "SlimedKensu"],
  [0x7b, "FishermanDaughter"],
  [0x7e, "Kensu"],
  [0x82, "AkahanaInBrynmaer"],
  [0x83, "AztecaInPyramid"],
  [0x84, "SaberaDisguisedAsMesia"],
  [0x85, "StonedWaterfallCaveAdventurers"],
  [0x88, "StonedAkahana"],
  [0x8e, "Mesia"],
  [0xc0, "Vampire1"],
  [0xc1, "Insect"],
  [0xc2, "Kelbesque1"],
  [0xc3, "Rage"],
  [0xc4, "Mado1"],
  [0xc5, "Kelbesque2"],
  [0xc6, "Sabera2"],
  [0xc7, "Mado2"],
  [0xc8, "Karmine"],
  [0xc9, "StatueOfMoon"],
  [0xca, "StatueOfSun"],
  [0xcb, "Draygon"],
  [0xcc, "Vampire2"],
];

// --------------------------------------------------------------- lookups

const LOCATION_BY_ID = new Map<number, string>(LOCATION_NAMES);
const OBJECT_BY_ID = new Map<number, string>(OBJECT_NAMES);
const NPC_BY_ID = new Map<number, string>(NPC_NAMES);

/** Symbolic name of a location, or `` if the slot is unused. */
export function locationName(id: number): string {
  return LOCATION_BY_ID.get(id) ?? '';
}

/**
 * Group a location belongs to, used to build the explorer tree.  Derived from
 * the part of the symbolic name before the first underscore.
 */
export function locationGroup(id: number): string {
  const name = locationName(id);
  if (!name) return 'Unused';
  const us = name.indexOf('_');
  return spaceCamelCase(us < 0 ? name : name.slice(0, us));
}

/** Short label for a location, without the group prefix. */
export function locationLabel(id: number): string {
  const name = locationName(id);
  if (!name) return `Location $${id.toString(16).padStart(2, '0')}`;
  const us = name.indexOf('_');
  return spaceCamelCase(us < 0 ? name : name.slice(us + 1));
}

/** `MtSabreWest` -> `Mt Sabre West`, `SealedCave1` -> `Sealed Cave 1`. */
export function spaceCamelCase(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
          .replace(/([A-Za-z])([0-9])/g, '$1 $2')
          .replace(/_/g, ' ');
}

/** Display name for a monster/object id, or `` if the disassembly names none. */
export function objectName(id: number): string {
  const name = OBJECT_BY_ID.get(id);
  return name ? titleCase(spaceCamelCase(name)) : '';
}

/** Display name for an NPC id, or `` if the disassembly names none. */
export function npcName(id: number): string {
  const name = NPC_BY_ID.get(id);
  return name ? titleCase(spaceCamelCase(name)) : '';
}

/** Most names come from camelCase variables, so the first word is lowercase. */
function titleCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
